version: '2'

services:
  joomla:
    build: site 
    links:
      - joomladb:mysql
    volumes:
      - $HOME/Sites/joomla-dev/importlabo-23-septembre-2015/www:/var/www/html/
    ports:
      - 8080:80
    environment:
      MYSQL_PORT_3306_TCP: 3306
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: juges3:sud
      JOOMLA_DB_USER: root
      JOOMLA_DB_NAME: jlabo

  joomladb:
    image: mysql:5.6
    volumes:
      - vc_subaweb_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: juges3:sud
      MYSQL_DATABASE: jlabo

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.6.3-1
    links:
      - joomladb
    ports:
      - 8081:80
    environment:
      PMA_HOST: joomladb

volumes:
  vc_subaweb_db:
    external: true

