#!/usr/bin/env sh

docker-compose -p $DOCKER_SUBAWEB_PROJECTNAME -f $DOCKER_SUBAWEB_SRC/docker-compose.yml up -d joomladb || exit 1

n="0"

while [ $n -lt 60 ]; do
	# try to access a database to know if mysql has indeed started
	docker run -i --rm \
		-v vc_${DOCKER_SUBAWEB_PROJECTNAME}_db:/var/lib/mysql \
		--net ${DOCKER_SUBAWEB_PROJECTNAME}_default \
		mysql:5.6 \
		mysql -uroot -hjoomladb -pjuges3:sud -e "use mysql"
	if [ $? -eq 0 ]; then
		echo "datedb is up after $n attempts"
		exit 0
	else
		sleep 1
	fi
	n=$(($n + 1))
done

exit 1
